# Generated by Django 6.0.3 on 2026-03-23 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_devices', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('diluent_code', models.CharField(blank=True, max_length=100, null=True)),
                ('lyse_code', models.CharField(blank=True, max_length=100, null=True)),
                ('cleaner_code', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_devices.device')),
            ],
        ),
    ]
