# Generated by Django 6.0.3 on 2026-03-24 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_devices', '0001_initial'),
        ('app_inventory', '0006_alter_inventorytransaction_options_recallnotice'),
        ('app_maintenance', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'زيارة صيانة', 'verbose_name_plural': 'زيارات الصيانة'},
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='cleaner_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='كود الكلينر'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_devices.device', verbose_name='الجهاز'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='diluent_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='كود الديلونت'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='lyse_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='كود اللايس'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='visit_date',
            field=models.DateField(verbose_name='تاريخ الزيارة'),
        ),
        migrations.CreateModel(
            name='MaintenanceItemUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية المستخدمة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.inventoryitem', verbose_name='الصنف')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventory.inventorylot', verbose_name='التشغيلة')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_items', to='app_maintenance.maintenance', verbose_name='زيارة الصيانة')),
            ],
            options={
                'verbose_name': 'صنف مستخدم في الصيانة',
                'verbose_name_plural': 'الأصناف المستخدمة في الصيانة',
            },
        ),
    ]
