# Generated by Django 6.0.3 on 2026-03-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_maintenance', '0002_alter_maintenance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-visit_date', '-id'], 'verbose_name': 'زيارة صيانة', 'verbose_name_plural': 'زيارات الصيانة'},
        ),
    ]
