# Generated by Django 6.0.3 on 2026-03-25 22:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_devices', '0002_alter_device_options_remove_device_name_and_more'),
        ('app_inventory', '0008_alter_inventoryitem_options_and_more'),
        ('app_maintenance', '0003_alter_maintenance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-visit_date', '-id'], 'verbose_name': 'صيانة', 'verbose_name_plural': 'الصيانات'},
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='cleaner_code',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='diluent_code',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='lyse_code',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف المشكلة / العمل'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='engineer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='المهندس'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('Preventive', 'دورية'), ('Corrective', 'عطل'), ('Installation', 'تركيب'), ('Training', 'تدريب')], default='Preventive', max_length=20, verbose_name='نوع الزيارة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='next_visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='الزيارة القادمة'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('Open', 'مفتوحة'), ('In Progress', 'قيد التنفيذ'), ('Closed', 'مغلقة')], default='Open', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='app_devices.device', verbose_name='الجهاز'),
        ),
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.inventoryitem', verbose_name='الصنف')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_maintenance.maintenance', verbose_name='الصيانة')),
            ],
            options={
                'verbose_name': 'عنصر صيانة',
                'verbose_name_plural': 'عناصر الصيانة',
            },
        ),
        migrations.DeleteModel(
            name='MaintenanceItemUsage',
        ),
    ]
