# Generated by Django 6.0.3 on 2026-03-25 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_devices', '0002_alter_device_options_remove_device_name_and_more'),
        ('app_inventory', '0008_alter_inventoryitem_options_and_more'),
        ('app_invoices', '0008_remove_invoiceprintsettings_address_and_more'),
        ('app_maintenance', '0004_alter_maintenance_options_and_more'),
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceitem',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='maintenanceitem',
            name='item',
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البلاغ')),
                ('reported_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم المُبلغ')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التواصل')),
                ('issue_description', models.TextField(verbose_name='وصف العطل / البلاغ')),
                ('priority', models.CharField(choices=[('Low', 'منخفضة'), ('Medium', 'متوسطة'), ('High', 'عالية'), ('Urgent', 'عاجلة')], default='Medium', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('New', 'جديد'), ('Assigned', 'تم التوزيع'), ('In Progress', 'قيد التنفيذ'), ('Waiting Approval', 'بانتظار موافقة العميل'), ('Waiting Parts', 'بانتظار قطع الغيار'), ('Resolved', 'تم الحل'), ('Closed', 'مغلق')], default='New', max_length=30, verbose_name='الحالة')),
                ('internal_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات داخلية')),
                ('customer_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات العميل')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='customers.customer', verbose_name='العميل')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='app_devices.device', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'طلب صيانة',
                'verbose_name_plural': 'طلبات الصيانة',
                'ordering': ['-request_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('Emergency', 'طارئة'), ('Preventive', 'دورية وقائية'), ('Follow-up', 'متابعة'), ('Installation', 'تركيب'), ('Training', 'تدريب')], max_length=30, verbose_name='نوع الزيارة')),
                ('status', models.CharField(choices=[('Open', 'مفتوحة'), ('Inspection Done', 'تم الفحص'), ('Waiting Approval', 'بانتظار موافقة العميل'), ('Waiting Parts', 'بانتظار قطع الغيار'), ('Scheduled Follow-up', 'مجدولة لزيارة أخرى'), ('Resolved', 'تم الحل'), ('Closed', 'مغلقة')], default='Open', max_length=30, verbose_name='الحالة')),
                ('visit_date', models.DateField(verbose_name='تاريخ الزيارة')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='الزيارة القادمة')),
                ('engineer_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم المهندس القائم بالعمل')),
                ('device_condition_before', models.TextField(blank=True, null=True, verbose_name='حالة الجهاز قبل الصيانة')),
                ('issue_found', models.TextField(blank=True, null=True, verbose_name='العطل / الملاحظات التي تم اكتشافها')),
                ('work_performed', models.TextField(blank=True, null=True, verbose_name='الأعمال التي تم تنفيذها')),
                ('device_condition_after', models.TextField(blank=True, null=True, verbose_name='حالة الجهاز بعد الصيانة')),
                ('final_result', models.TextField(blank=True, null=True, verbose_name='النتيجة النهائية / ملخص التقرير الفني')),
                ('issue_resolved', models.BooleanField(default=False, verbose_name='هل تم حل المشكلة؟')),
                ('needs_spare_parts', models.BooleanField(default=False, verbose_name='هل يحتاج قطع غيار؟')),
                ('requires_customer_approval', models.BooleanField(default=False, verbose_name='هل يحتاج موافقة العميل على عرض السعر؟')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_visits', to='customers.customer', verbose_name='العميل')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_visits', to='app_devices.device', verbose_name='الجهاز')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='app_maintenance.maintenancerequest', verbose_name='طلب الصيانة')),
            ],
            options={
                'verbose_name': 'زيارة صيانة',
                'verbose_name_plural': 'زيارات الصيانة',
                'ordering': ['-visit_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية المطلوبة')),
                ('availability_status', models.CharField(choices=[('Unknown', 'غير محدد'), ('Available', 'متاح'), ('Not Available', 'غير متاح'), ('Ordered', 'تم طلبه')], default='Unknown', max_length=20, verbose_name='حالة التوفر')),
                ('quotation_required', models.BooleanField(default=False, verbose_name='هل يحتاج عرض سعر؟')),
                ('quotation_status', models.CharField(choices=[('Not Needed', 'لا يحتاج عرض سعر'), ('Draft', 'قيد الإعداد'), ('Sent', 'تم الإرسال'), ('Approved', 'تمت الموافقة'), ('Rejected', 'مرفوض')], default='Not Needed', max_length=20, verbose_name='حالة عرض السعر')),
                ('approved_by_customer', models.BooleanField(default=False, verbose_name='تمت موافقة العميل')),
                ('installed', models.BooleanField(default=False, verbose_name='تم التركيب')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.inventoryitem', verbose_name='الصنف / قطعة الغيار')),
                ('linked_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requirements', to='app_invoices.invoice', verbose_name='الفاتورة المرتبطة')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='app_maintenance.maintenancevisit', verbose_name='الزيارة')),
            ],
            options={
                'verbose_name': 'احتياج صيانة / قطعة مطلوبة',
                'verbose_name_plural': 'احتياجات الصيانة / القطع المطلوبة',
            },
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='MaintenanceItem',
        ),
    ]
