# Generated by Django 6.0.3 on 2026-03-25 23:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_devices', '0002_alter_device_options_remove_device_name_and_more'),
        ('app_maintenance', '0005_remove_maintenanceitem_maintenance_and_more'),
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancevisit',
            name='signed_report_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التقرير الموقع'),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='signed_report_received',
            field=models.BooleanField(default=False, verbose_name='تم استلام تقرير موقع من العميل'),
        ),
        migrations.AlterField(
            model_name='maintenancerequirement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='الكمية المطلوبة'),
        ),
        migrations.AlterField(
            model_name='maintenancevisit',
            name='final_result',
            field=models.TextField(blank=True, null=True, verbose_name='النتيجة النهائية / التقرير الفني'),
        ),
        migrations.AlterField(
            model_name='maintenancevisit',
            name='issue_found',
            field=models.TextField(blank=True, null=True, verbose_name='العطل / الملاحظات المكتشفة'),
        ),
        migrations.AlterField(
            model_name='maintenancevisit',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الزيارة'),
        ),
        migrations.CreateModel(
            name='PreventiveMaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='الخطة مفعلة')),
                ('interval_type', models.CharField(choices=[('Monthly', 'شهري'), ('Quarterly', 'كل 3 شهور'), ('SemiAnnual', 'كل 6 شهور'), ('Annual', 'سنوي'), ('CustomDays', 'عدد أيام مخصص')], default='Quarterly', max_length=20, verbose_name='نوع الفترة')),
                ('interval_days', models.PositiveIntegerField(default=90, verbose_name='عدد الأيام')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='بداية الجدول')),
                ('last_visit_date', models.DateField(blank=True, null=True, verbose_name='آخر زيارة وقائية')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='موعد الزيارة القادمة')),
                ('grace_days', models.PositiveIntegerField(default=0, verbose_name='فترة سماح بالأيام')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإدارة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventive_plans', to='customers.customer', verbose_name='العميل')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preventive_plan', to='app_devices.device', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'خطة صيانة وقائية',
                'verbose_name_plural': 'خطط الصيانة الوقائية',
                'ordering': ['next_due_date', 'device__device_name'],
            },
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='preventive_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='app_maintenance.preventivemaintenanceplan', verbose_name='خطة الصيانة الوقائية'),
        ),
    ]
