# Generated by Django 6.0.3 on 2026-03-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maintenance', '0006_maintenancevisit_signed_report_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancevisit',
            name='cleaner_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='كود الـ Cleaner المستخدم/المفعل'),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='cleaner_lot',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lot / Batch للـ Cleaner'),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='completed_on_time',
            field=models.BooleanField(default=False, verbose_name='تمت في الموعد'),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='diluent_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='كود الـ Diluent المستخدم/المفعل'),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='diluent_lot',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lot / Batch للـ Diluent'),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='lyse_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='كود الـ Lyse المستخدم/المفعل'),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='lyse_lot',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lot / Batch للـ Lyse'),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='planned_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='الموعد الوقائي المستهدف'),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='reagents_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات المحاليل وقت الزيارة'),
        ),
    ]
