# Generated by Django 6.0.3 on 2026-03-27 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employees', '0002_employee_sales_commission_percent'),
        ('app_maintenance', '0007_maintenancevisit_cleaner_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancevisit',
            name='cleaner_code',
        ),
        migrations.RemoveField(
            model_name='maintenancevisit',
            name='cleaner_lot',
        ),
        migrations.RemoveField(
            model_name='maintenancevisit',
            name='completed_on_time',
        ),
        migrations.RemoveField(
            model_name='maintenancevisit',
            name='diluent_code',
        ),
        migrations.RemoveField(
            model_name='maintenancevisit',
            name='diluent_lot',
        ),
        migrations.RemoveField(
            model_name='maintenancevisit',
            name='lyse_code',
        ),
        migrations.RemoveField(
            model_name='maintenancevisit',
            name='lyse_lot',
        ),
        migrations.RemoveField(
            model_name='maintenancevisit',
            name='planned_due_date',
        ),
        migrations.RemoveField(
            model_name='maintenancevisit',
            name='reagents_notes',
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_visits', to='app_employees.employee', verbose_name='المهندس المسؤول'),
        ),
    ]
