# Generated by Django 6.0.3 on 2026-03-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0007_alter_inventorytransaction_source_type'),
        ('app_invoices', '0002_remove_invoice_customer_remove_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'فاتورة', 'verbose_name_plural': 'الفواتير'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'بند فاتورة', 'verbose_name_plural': 'بنود الفاتورة'},
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventory.inventorylot', verbose_name='التشغيلة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_invoices.invoice', verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية'),
        ),
    ]
