# Generated by Django 6.0.3 on 2026-03-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoices', '0003_alter_invoice_options_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-id'], 'verbose_name': 'فاتورة', 'verbose_name_plural': 'الفواتير'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الخصم'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم %'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='net_before_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي بعد الخصم وقبل الضريبة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي قبل الخصم'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_after_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي النهائي'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الضريبة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=14, max_digits=5, verbose_name='نسبة ضريبة القيمة المضافة %'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي البند'),
        ),
    ]
