# Generated by Django 6.0.3 on 2026-03-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoices', '0004_alter_invoice_options_remove_invoice_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='net_before_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الصافي قبل الضريبة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=14, max_digits=5, verbose_name='نسبة الضريبة %'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة'),
        ),
    ]
