# Generated by Django 6.0.3 on 2026-03-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoices', '0005_invoice_notes_alter_invoice_net_before_vat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePrintSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Analytech', max_length=200, verbose_name='اسم الشركة')),
                ('company_subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='وصف الشركة')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='الهاتف')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='البريد الإلكتروني')),
                ('website', models.CharField(blank=True, max_length=150, null=True, verbose_name='الموقع الإلكتروني')),
                ('header_text', models.TextField(blank=True, null=True, verbose_name='نص إضافي في الهيدر')),
                ('footer_text', models.TextField(blank=True, null=True, verbose_name='نص إضافي في الفوتر')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='invoice_assets/', verbose_name='لوجو الشركة')),
                ('extra_image', models.ImageField(blank=True, null=True, upload_to='invoice_assets/', verbose_name='صورة إضافية')),
            ],
            options={
                'verbose_name': 'إعدادات طباعة الفواتير',
                'verbose_name_plural': 'إعدادات طباعة الفواتير',
            },
        ),
    ]
