# Generated by Django 6.0.3 on 2026-03-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoices', '0006_invoiceprintsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceprintsettings',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='invoiceprintsettings',
            name='header_text',
        ),
        migrations.AddField(
            model_name='invoiceprintsettings',
            name='footer_text_ar',
            field=models.TextField(blank=True, null=True, verbose_name='نص الفوتر عربي'),
        ),
        migrations.AddField(
            model_name='invoiceprintsettings',
            name='footer_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='نص الفوتر English'),
        ),
        migrations.AlterField(
            model_name='invoiceprintsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_assets/', verbose_name='صورة الهيدر'),
        ),
    ]
