# Generated by Django 6.0.3 on 2026-03-25 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0008_alter_inventoryitem_options_and_more'),
        ('app_invoices', '0007_remove_invoiceprintsettings_footer_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceprintsettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='invoiceprintsettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='invoiceprintsettings',
            name='extra_image',
        ),
        migrations.RemoveField(
            model_name='invoiceprintsettings',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='invoiceprintsettings',
            name='website',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_inventory.inventoryitem', verbose_name='الصنف'),
        ),
    ]
