# Generated by Django 6.0.3 on 2026-03-26 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_invoices', '0008_remove_invoiceprintsettings_address_and_more'),
        ('app_quotations', '0002_remove_quotationitem_device_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='app_quotations.quotation', verbose_name='عرض السعر'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحلة'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stock_posted',
            field=models.BooleanField(default=False, verbose_name='تم ترحيل المخزن'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف البند'),
        ),
    ]
