# Generated by Django 6.0.3 on 2026-03-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_journalentry_account_journalentryline_paymentvoucher_and_more'),
        ('app_invoices', '0009_invoice_quotation_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='accounting.journalentry', verbose_name='القيد المحاسبي'),
        ),
    ]
