# Generated by Django 6.0.3 on 2026-03-27 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employees', '0002_employee_sales_commission_percent'),
        ('app_invoices', '0010_invoice_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='commission_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_invoices', to='app_employees.employee', verbose_name='صاحب العمولة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='app_employees.employee', verbose_name='الموظف المسؤول عن البيع'),
        ),
    ]
