# Generated by Django 6.0.3 on 2026-03-26 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_devices', '0002_alter_device_options_remove_device_name_and_more'),
        ('app_inventory', '0008_alter_inventoryitem_options_and_more'),
        ('app_maintenance', '0006_maintenancevisit_signed_report_date_and_more'),
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_type', models.CharField(choices=[('Devices', 'أجهزة'), ('Consumables', 'محاليل ومستلزمات'), ('Spare Parts', 'قطع غيار'), ('Service', 'خدمة / صيانة'), ('Mixed', 'مختلط'), ('Other', 'أخرى')], default='Mixed', max_length=30, verbose_name='نوع عرض السعر')),
                ('status', models.CharField(choices=[('Draft', 'مسودة'), ('Sent', 'تم الإرسال'), ('Approved', 'تمت الموافقة'), ('Rejected', 'مرفوض'), ('Expired', 'منتهي'), ('Converted', 'تم التحويل إلى فاتورة')], default='Draft', max_length=20, verbose_name='الحالة')),
                ('quotation_date', models.DateField(auto_now_add=True, verbose_name='تاريخ العرض')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='ساري حتى')),
                ('reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='مرجع')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='موضوع العرض')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي قبل الخصم')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم %')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الخصم')),
                ('net_before_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الصافي قبل الضريبة')),
                ('vat_percent', models.DecimalField(decimal_places=2, default=14, max_digits=5, verbose_name='نسبة الضريبة %')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الضريبة')),
                ('total_after_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي النهائي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('terms', models.TextField(blank=True, null=True, verbose_name='الشروط والأحكام')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='customers.customer', verbose_name='العميل')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='app_devices.device', verbose_name='الجهاز')),
                ('maintenance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='app_maintenance.maintenancerequest', verbose_name='طلب الصيانة المرتبط')),
                ('maintenance_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='app_maintenance.maintenancevisit', verbose_name='زيارة الصيانة المرتبطة')),
            ],
            options={
                'verbose_name': 'عرض سعر',
                'verbose_name_plural': 'عروض الأسعار',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Device', 'جهاز'), ('Inventory', 'صنف مخزني'), ('Service', 'خدمة'), ('Visit', 'زيارة'), ('Other', 'أخرى')], default='Other', max_length=20, verbose_name='نوع البند')),
                ('description', models.CharField(max_length=255, verbose_name='وصف البند')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر الوحدة')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي البند')),
                ('device_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_quotation_items', to='app_devices.device', verbose_name='الجهاز المرجعي')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='app_inventory.inventoryitem', verbose_name='الصنف المخزني')),
                ('maintenance_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='app_maintenance.maintenancerequirement', verbose_name='احتياج الصيانة المرتبط')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_quotations.quotation', verbose_name='عرض السعر')),
            ],
            options={
                'verbose_name': 'بند عرض سعر',
                'verbose_name_plural': 'بنود عروض الأسعار',
            },
        ),
    ]
