# Generated by Django 6.0.3 on 2026-03-26 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_devices', '0002_alter_device_options_remove_device_name_and_more'),
        ('app_quotations', '0001_initial'),
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='device_product',
        ),
        migrations.AddField(
            model_name='quotation',
            name='contact_person_manual',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='الشخص المسؤول يدويًا'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_address_manual',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان العميل اليدوي'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_name_manual',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم العميل اليدوي'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_phone_manual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='هاتف العميل اليدوي'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='customers.customer', verbose_name='العميل المسجل'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='app_devices.device', verbose_name='الجهاز المرجعي'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='subject',
            field=models.CharField(default='عرض سعرط', max_length=255, verbose_name='موضوع العرض'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='item_type',
            field=models.CharField(choices=[('Product', 'منتج'), ('Device', 'جهاز'), ('Spare Part', 'قطعة غيار'), ('Consumable', 'محلول / مستهلك'), ('Service', 'خدمة'), ('Visit', 'زيارة'), ('Other', 'أخرى')], default='Product', max_length=20, verbose_name='نوع البند'),
        ),
    ]
