# Generated by Django 6.0.3 on 2026-03-26 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_journalentry_account_journalentryline_paymentvoucher_and_more'),
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='accounting.account', verbose_name='الحساب المحاسبي'),
        ),
    ]
