# Generated by Django 6.0.3 on 2026-03-24 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_devices', '0001_initial'),
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['device_name', 'serial_number'], 'verbose_name': 'جهاز', 'verbose_name_plural': 'الأجهزة'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='جهاز قديم', max_length=200, verbose_name='اسم الجهاز'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('CBC', 'CBC'), ('Chemistry', 'Chemistry'), ('Immunoassay', 'Immunoassay'), ('Coagulation', 'Coagulation'), ('Other', 'Other')], default='CBC', max_length=50, verbose_name='نوع الجهاز'),
        ),
        migrations.AddField(
            model_name='device',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التركيب'),
        ),
        migrations.AddField(
            model_name='device',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='device',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='نهاية الضمان'),
        ),
        migrations.AlterField(
            model_name='device',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='customers.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='الموديل'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=150, unique=True, verbose_name='السيريال نمبر'),
        ),
    ]
