# Generated by Django 6.0.3 on 2026-03-27 12:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_invoices', '0010_invoice_journal_entry'),
        ('app_quotations', '0002_remove_quotationitem_device_product_and_more'),
        ('customers', '0003_customer_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50, unique=True, verbose_name='كود الموظف')),
                ('full_name', models.CharField(max_length=200, verbose_name='اسم الموظف')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='القسم')),
                ('job_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='الوظيفة')),
                ('status', models.CharField(choices=[('Active', 'نشط'), ('On Leave', 'إجازة'), ('Suspended', 'موقوف'), ('Resigned', 'مستقيل')], default='Active', max_length=20, verbose_name='الحالة')),
                ('hire_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ التعيين')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم القومي')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='الموبايل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('qualification', models.CharField(blank=True, max_length=200, null=True, verbose_name='المؤهل الدراسي')),
                ('specialization', models.CharField(blank=True, max_length=200, null=True, verbose_name='التخصص')),
                ('can_do_sales', models.BooleanField(default=False, verbose_name='يمكنه تنفيذ مبيعات')),
                ('can_do_service', models.BooleanField(default=False, verbose_name='يمكنه تنفيذ صيانة')),
                ('can_manage_team', models.BooleanField(default=False, verbose_name='يمكنه إدارة فريق')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('direct_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='app_employees.employee', verbose_name='المدير المباشر')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ السلفة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة السلفة')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='البيان')),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المسدد منها')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='app_employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سلفة',
                'verbose_name_plural': 'السلف',
                'ordering': ['-advance_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الحافز/المكافأة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='القيمة')),
                ('reason', models.CharField(max_length=255, verbose_name='السبب')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='app_employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'حافز / مكافأة',
                'verbose_name_plural': 'الحوافز والمكافآت',
                'ordering': ['-bonus_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ العمولة')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الأساس')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة العمولة %')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة العمولة')),
                ('status', models.CharField(choices=[('Draft', 'مسودة'), ('Approved', 'معتمدة'), ('Paid', 'مدفوعة'), ('Cancelled', 'ملغاة')], default='Draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_commissions', to='customers.customer', verbose_name='العميل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='app_employees.employee', verbose_name='الموظف')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_commissions', to='app_invoices.invoice', verbose_name='الفاتورة')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_commissions', to='app_quotations.quotation', verbose_name='عرض السعر')),
            ],
            options={
                'verbose_name': 'عمولة',
                'verbose_name_plural': 'العمولات',
                'ordering': ['-commission_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المرتب الأساسي')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدل انتقال')),
                ('phone_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدل موبايل')),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدل سكن')),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدلات أخرى')),
                ('payment_method', models.CharField(choices=[('Cash', 'نقدي'), ('Bank', 'بنك'), ('Transfer', 'تحويل'), ('Other', 'أخرى')], default='Cash', max_length=20, verbose_name='طريقة الصرف')),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم البنك')),
                ('bank_account', models.CharField(blank=True, max_length=150, null=True, verbose_name='رقم الحساب')),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='ساري من')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compensation', to='app_employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'بيانات مالية للموظف',
                'verbose_name_plural': 'البيانات المالية للموظفين',
            },
        ),
        migrations.CreateModel(
            name='EmployeeExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ المصروف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='القيمة')),
                ('expense_type', models.CharField(choices=[('Transport', 'انتقالات'), ('Meals', 'إقامة / وجبات'), ('Maintenance', 'مصروفات تشغيل'), ('Sales', 'مصروفات مبيعات'), ('Other', 'أخرى')], default='Other', max_length=30, verbose_name='نوع المصروف')),
                ('description', models.CharField(max_length=255, verbose_name='البيان')),
                ('approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_claims', to='app_employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'مصروف مسترد',
                'verbose_name_plural': 'المصروفات المستردة',
                'ordering': ['-expense_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الجزاء')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة الجزاء')),
                ('reason', models.CharField(max_length=255, verbose_name='سبب الجزاء')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='app_employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'جزاء',
                'verbose_name_plural': 'الجزاءات',
                'ordering': ['-penalty_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('Sales Rep', 'مندوب مبيعات'), ('Sales Manager', 'مدير مبيعات'), ('Service Engineer', 'مهندس صيانة'), ('Service Manager', 'مدير صيانة'), ('Accountant', 'محاسب'), ('Admin', 'إداري'), ('Other', 'أخرى')], max_length=50, verbose_name='الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='app_employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'دور موظف',
                'verbose_name_plural': 'أدوار الموظفين',
            },
        ),
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(verbose_name='الشهر')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الأساسي')),
                ('allowances_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي البدلات')),
                ('bonuses_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الحوافز')),
                ('commissions_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي العمولات')),
                ('expenses_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المصروفات')),
                ('penalties_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الجزاءات')),
                ('advances_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي السلف')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='صافي المستحق')),
                ('status', models.CharField(choices=[('Draft', 'مسودة'), ('Approved', 'معتمد'), ('Paid', 'مدفوع')], default='Draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='app_employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'مسير راتب',
                'verbose_name_plural': 'مسيرات الرواتب',
                'ordering': ['-year', '-month', 'employee__full_name'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
