# Generated by Django 6.0.3 on 2026-03-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sales_commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة عمولة المبيعات الافتراضية %'),
        ),
    ]
