# Generated by Django 6.0.3 on 2026-03-26 17:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ القيد')),
                ('description', models.CharField(max_length=255, verbose_name='البيان')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='المرجع')),
                ('status', models.CharField(choices=[('Draft', 'مسودة'), ('Posted', 'مرحّل'), ('Cancelled', 'ملغي')], default='Draft', max_length=20, verbose_name='الحالة')),
                ('source_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع المصدر')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'القيود اليومية',
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الحساب')),
                ('account_type', models.CharField(choices=[('Asset', 'أصل'), ('Liability', 'التزام'), ('Equity', 'حقوق ملكية'), ('Revenue', 'إيراد'), ('Expense', 'مصروف')], max_length=20, verbose_name='نوع الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.account', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'شجرة الحسابات',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='بيان السطر')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='دائن')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_lines', to='accounting.account', verbose_name='الحساب')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='القيد')),
            ],
            options={
                'verbose_name': 'سطر قيد',
                'verbose_name_plural': 'سطور القيود',
            },
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('payee_name', models.CharField(max_length=200, verbose_name='اسم المستفيد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('Cash', 'نقدي'), ('Bank', 'بنك'), ('Cheque', 'شيك'), ('Transfer', 'تحويل'), ('Other', 'أخرى')], default='Cash', max_length=20, verbose_name='طريقة السداد')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='المرجع')),
                ('description', models.CharField(max_length=255, verbose_name='البيان')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_credit_vouchers', to='accounting.account', verbose_name='الحساب الدائن')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_debit_vouchers', to='accounting.account', verbose_name='الحساب المدين')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_voucher', to='accounting.journalentry', verbose_name='القيد المرتبط')),
            ],
            options={
                'verbose_name': 'سند صرف',
                'verbose_name_plural': 'سندات الصرف',
                'ordering': ['-voucher_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('payer_name', models.CharField(max_length=200, verbose_name='اسم الدافع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('Cash', 'نقدي'), ('Bank', 'بنك'), ('Cheque', 'شيك'), ('Transfer', 'تحويل'), ('Other', 'أخرى')], default='Cash', max_length=20, verbose_name='طريقة السداد')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='المرجع')),
                ('description', models.CharField(max_length=255, verbose_name='البيان')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_credit_vouchers', to='accounting.account', verbose_name='الحساب الدائن')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_debit_vouchers', to='accounting.account', verbose_name='الحساب المدين')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_voucher', to='accounting.journalentry', verbose_name='القيد المرتبط')),
            ],
            options={
                'verbose_name': 'سند قبض',
                'verbose_name_plural': 'سندات القبض',
                'ordering': ['-voucher_date', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
