# Generated by Django 6.0.3 on 2026-03-26 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_journalentry_account_journalentryline_paymentvoucher_and_more'),
        ('customers', '0003_customer_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptvoucher',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_vouchers', to='customers.customer', verbose_name='العميل'),
        ),
    ]
