# Generated by Django 6.0.3 on 2026-03-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
