# Generated by Django 6.0.3 on 2026-03-27 21:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_employees', '0002_employee_sales_commission_percent'),
        ('app_inventory', '0008_alter_inventoryitem_options_and_more'),
        ('app_invoices', '0011_invoice_commission_owner_invoice_sales_owner'),
        ('app_quotations', '0003_quotation_commission_owner_quotation_sales_owner'),
        ('customers', '0003_customer_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الطلب')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='التاريخ المطلوب')),
                ('status', models.CharField(choices=[('Draft', 'مسودة'), ('Confirmed', 'معتمد'), ('Ready', 'جاهز للصرف'), ('Partially Released', 'صرف جزئي'), ('Released', 'تم الصرف'), ('Shipped', 'تم الشحن'), ('Delivered', 'تم التسليم'), ('Closed', 'مغلق'), ('Cancelled', 'ملغي')], default='Draft', max_length=30, verbose_name='الحالة')),
                ('payment_terms', models.CharField(choices=[('Cash Before Delivery', 'نقدي قبل التسليم'), ('Cash On Delivery', 'نقدي عند التسليم'), ('Credit', 'آجل'), ('Bank Transfer', 'تحويل بنكي'), ('Mixed', 'مختلط')], default='Credit', max_length=30, verbose_name='شروط السداد')),
                ('delivery_method', models.CharField(choices=[('Internal Employee', 'مندوب من موظفي الشركة'), ('External Courier', 'شركة شحن'), ('External Representative', 'مندوب خارجي'), ('Customer Pickup', 'استلام من العميل')], default='Internal Employee', max_length=30, verbose_name='طريقة التوصيل')),
                ('external_courier_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم شركة الشحن')),
                ('external_representative_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المندوب الخارجي')),
                ('external_representative_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='هاتف المندوب الخارجي')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='عنوان التوصيل')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الشحنة / التتبع')),
                ('shipping_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='رسوم الشحن')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الصرف من المخزن')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الشحن / الخروج')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('customer_confirmed_receipt', models.BooleanField(default=False, verbose_name='تم تأكيد استلام العميل')),
                ('customer_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ تأكيد الاستلام')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='customers.customer', verbose_name='العميل')),
                ('internal_delivery_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='app_employees.employee', verbose_name='مندوب التوصيل الداخلي')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='app_invoices.invoice', verbose_name='الفاتورة')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='app_quotations.quotation', verbose_name='عرض السعر')),
                ('sales_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='app_employees.employee', verbose_name='الموظف المسؤول عن الطلب')),
            ],
            options={
                'verbose_name': 'طلب بيع',
                'verbose_name_plural': 'طلبات البيع',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية المطلوبة')),
                ('qty_released', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية المنصرفة')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر الوحدة')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_items', to='app_inventory.inventoryitem', verbose_name='الصنف')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_items', to='app_inventory.inventorylot', verbose_name='التشغيلة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_sales.salesorder', verbose_name='طلب البيع')),
            ],
            options={
                'verbose_name': 'بند طلب بيع',
                'verbose_name_plural': 'بنود طلبات البيع',
            },
        ),
    ]
