# Generated by Django 6.0.3 on 2026-03-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='اسم الصنف')),
                ('item_type', models.CharField(choices=[('Spare Part', 'قطعة غيار'), ('Diluent', 'Diluent'), ('Lyse', 'Lyse'), ('Cleaner', 'Cleaner'), ('Control', 'Control'), ('Calibrator', 'Calibrator'), ('Other', 'أخرى')], max_length=50, verbose_name='نوع الصنف')),
                ('item_code', models.CharField(max_length=100, unique=True, verbose_name='كود الصنف')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='الوحدة')),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lot Number')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الحد الأدنى')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر الشراء')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر البيع')),
                ('supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='المورد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'صنف مخزني',
                'verbose_name_plural': 'أصناف المخزن',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
