# Generated by Django 6.0.3 on 2026-03-23 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0002_inventoryitem_delete_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={},
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'وارد'), ('OUT', 'منصرف'), ('ADJUSTMENT', 'تسوية')], max_length=20, verbose_name='نوع الحركة')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية')),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرصيد قبل')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرصيد بعد')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة')),
                ('reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='المرجع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app_inventory.inventoryitem', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'صنف مخزني',
                'verbose_name_plural': 'أصناف المخزن',
            },
        ),
    ]
