# Generated by Django 6.0.3 on 2026-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0003_alter_inventoryitem_options_inventorytransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'صنف مخزني', 'verbose_name_plural': 'أصناف المخزن'},
        ),
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ['-transaction_date'], 'verbose_name': 'حركة مخزنية', 'verbose_name_plural': 'حركات المخزن'},
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='source_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المصدر / المرجع'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='source_type',
            field=models.CharField(blank=True, choices=[('Supplier', 'مورد'), ('Customer Return', 'مرتجع عميل'), ('Maintenance Return', 'مرتجع صيانة'), ('Adjustment', 'تسوية'), ('Other', 'أخرى')], max_length=30, null=True, verbose_name='مصدر الحركة'),
        ),
    ]
