# Generated by Django 6.0.3 on 2026-03-24 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0004_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100, verbose_name='رقم التشغيلة')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='app_inventory.inventoryitem', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'تشغيلة',
                'verbose_name_plural': 'التشغيلات',
            },
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inventory.inventorylot', verbose_name='التشغيلة'),
        ),
    ]
