# Generated by Django 6.0.3 on 2026-03-24 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0005_inventorylot_inventorytransaction_lot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ['transaction_date', 'id'], 'verbose_name': 'حركة مخزنية', 'verbose_name_plural': 'حركات المخزن'},
        ),
        migrations.CreateModel(
            name='RecallNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recall_number', models.CharField(max_length=100, unique=True, verbose_name='رقم إشعار السحب')),
                ('notice_date', models.DateField(verbose_name='تاريخ الإشعار')),
                ('reason', models.TextField(verbose_name='سبب السحب')),
                ('risk_level', models.CharField(choices=[('Low', 'منخفض'), ('Medium', 'متوسط'), ('High', 'مرتفع'), ('Critical', 'حرج')], max_length=20, verbose_name='درجة الخطورة')),
                ('status', models.CharField(choices=[('Open', 'مفتوح'), ('In Progress', 'قيد التنفيذ'), ('Closed', 'مغلق')], default='Open', max_length=20, verbose_name='الحالة')),
                ('action_required', models.TextField(blank=True, null=True, verbose_name='الإجراء المطلوب')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.inventoryitem', verbose_name='الصنف')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.inventorylot', verbose_name='التشغيلة')),
            ],
            options={
                'verbose_name': 'إشعار سحب',
                'verbose_name_plural': 'إشعارات السحب',
            },
        ),
    ]
