# Generated by Django 6.0.3 on 2026-03-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0006_alter_inventorytransaction_options_recallnotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='source_type',
            field=models.CharField(blank=True, choices=[('Supplier', 'مورد'), ('Customer', 'عميل'), ('Customer Return', 'مرتجع عميل'), ('Maintenance Return', 'مرتجع صيانة'), ('Adjustment', 'تسوية'), ('Other', 'أخرى')], max_length=30, null=True, verbose_name='مصدر الحركة'),
        ),
    ]
