# Generated by Django 6.0.3 on 2026-03-24 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0007_alter_inventorytransaction_source_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['item_name'], 'verbose_name': 'صنف مخزني', 'verbose_name_plural': 'أصناف المخزن'},
        ),
        migrations.AlterModelOptions(
            name='inventorylot',
            options={'ordering': ['expiry_date', 'created_at', 'id'], 'verbose_name': 'تشغيلة', 'verbose_name_plural': 'التشغيلات'},
        ),
        migrations.AlterModelOptions(
            name='recallnotice',
            options={'ordering': ['-notice_date', 'recall_number'], 'verbose_name': 'إشعار سحب', 'verbose_name_plural': 'إشعارات السحب'},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='lot_number',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الكمية'),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='كمية التشغيلة'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_inventory.inventorylot', verbose_name='التشغيلة'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='source_type',
            field=models.CharField(blank=True, choices=[('Supplier', 'مورد'), ('Customer', 'عميل'), ('Customer Return', 'مرتجع عميل'), ('Maintenance', 'صيانة'), ('Maintenance Return', 'مرتجع صيانة'), ('Adjustment', 'تسوية'), ('Other', 'أخرى')], max_length=30, null=True, verbose_name='مصدر الحركة'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorylot',
            unique_together={('item', 'lot_number')},
        ),
    ]
